//! Embed the Windows icon and version metadata into `sweep.exe`.
//!
//! Windows is the one platform where the executable carries user-visible
//! metadata of its own: Explorer, the taskbar and the Alt-Tab switcher read
//! the icon and the version block straight out of the PE resources.
//!
//! There is deliberately no application manifest here. The GNU toolchain
//! already links mingw-w64's `default-manifest.o`, which declares
//! `requestedExecutionLevel="asInvoker"` and `longPathAware`, and a second
//! manifest resource makes `ld` warn and leaves it ambiguous which one
//! Windows uses. The one thing that manifest lacks — a UTF-8 console code
//! page — is set at runtime by `platform::windows::init_console` instead.
//!
//! Rather than pull in a resource crate, this calls the toolchain's own
//! resource compiler (`windres` for the GNU target, which is what this
//! project builds with on Windows). If it is missing the build still
//! succeeds with a warning — a missing icon must never break a release.

use std::path::{Path, PathBuf};
use std::process::Command;

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=packaging/windows/sweep.ico");

    // Only Windows binaries carry PE resources.
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() != Ok("windows") {
        return;
    }

    // MSVC's linker already embeds its own manifest and rejects a second one,
    // and this project ships the GNU build; do not guess at an untested path.
    if std::env::var("CARGO_CFG_TARGET_ENV").as_deref() != Ok("gnu") {
        println!(
            "cargo:warning=Windows resource embedding (icon, version info) is wired for the \
             *-pc-windows-gnu target; skipping for this target."
        );
        return;
    }

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"));
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let icon = root.join("packaging").join("windows").join("sweep.ico");

    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.0.0".into());
    let rc_path = out_dir.join("sweep_resources.rc");
    let rc_source = resource_script(&icon, &version);
    if let Err(err) = std::fs::write(&rc_path, rc_source) {
        println!("cargo:warning=could not write the resource script: {err}");
        return;
    }

    match compile_resource(&rc_path, &out_dir) {
        Ok(object) => {
            println!("cargo:rustc-link-arg-bins={}", object.display());
        }
        Err(reason) => {
            println!(
                "cargo:warning=could not embed Windows resources ({reason}); \
                 sweep.exe will build without an icon or version block"
            );
        }
    }
}

/// `"0.2.5"` (or `"0.2.5-rc1"`) into the four `u16` fields a `VERSIONINFO`
/// needs.
fn version_quad(version: &str) -> (u16, u16, u16, u16) {
    let core = version.split(['-', '+']).next().unwrap_or(version);
    let mut parts = core.split('.').map(|p| p.parse::<u16>().unwrap_or(0));
    (
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
        parts.next().unwrap_or(0),
    )
}

/// The `.rc` script: the main icon plus a `VERSIONINFO` block.
fn resource_script(icon: &Path, version: &str) -> String {
    let (a, b, c, d) = version_quad(version);
    let description = std::env::var("CARGO_PKG_DESCRIPTION").unwrap_or_default();
    let authors = std::env::var("CARGO_PKG_AUTHORS").unwrap_or_default();
    let license = std::env::var("CARGO_PKG_LICENSE").unwrap_or_default();

    let mut rc = String::new();
    rc.push_str("/* Generated by build.rs - do not edit. */\n");
    rc.push_str("#include <windows.h>\n\n");

    // Resource id 1 is the icon Windows shows for the executable.
    if icon.is_file() {
        rc.push_str(&format!("1 ICON \"{}\"\n\n", rc_path(icon)));
    } else {
        println!(
            "cargo:warning={} is missing; sweep.exe will have no icon \
             (regenerate it with: python packaging/windows/make-ico.py)",
            icon.display()
        );
    }

    rc.push_str(&format!(
        "VS_VERSION_INFO VERSIONINFO\n\
         FILEVERSION {a},{b},{c},{d}\n\
         PRODUCTVERSION {a},{b},{c},{d}\n\
         FILEFLAGSMASK 0x3fL\n\
         FILEFLAGS 0x0L\n\
         FILEOS 0x40004L\n\
         FILETYPE 0x1L\n\
         FILESUBTYPE 0x0L\n\
         BEGIN\n\
         \x20   BLOCK \"StringFileInfo\"\n\
         \x20   BEGIN\n\
         \x20       BLOCK \"040904b0\"\n\
         \x20       BEGIN\n\
         \x20           VALUE \"CompanyName\", \"{authors}\\0\"\n\
         \x20           VALUE \"FileDescription\", \"{description}\\0\"\n\
         \x20           VALUE \"FileVersion\", \"{version}\\0\"\n\
         \x20           VALUE \"InternalName\", \"sweep\\0\"\n\
         \x20           VALUE \"LegalCopyright\", \"{license}\\0\"\n\
         \x20           VALUE \"OriginalFilename\", \"sweep.exe\\0\"\n\
         \x20           VALUE \"ProductName\", \"Sweep\\0\"\n\
         \x20           VALUE \"ProductVersion\", \"{version}\\0\"\n\
         \x20       END\n\
         \x20   END\n\
         \x20   BLOCK \"VarFileInfo\"\n\
         \x20   BEGIN\n\
         \x20       VALUE \"Translation\", 0x409, 1200\n\
         \x20   END\n\
         END\n"
    ));
    rc
}

/// Resource scripts treat backslashes as escapes; forward slashes work on
/// Windows too and remove the ambiguity.
fn rc_path(path: &Path) -> String {
    path.to_string_lossy().replace('\\', "/")
}

/// Compile the `.rc` into a COFF object the linker can take.
fn compile_resource(rc: &Path, out_dir: &Path) -> Result<PathBuf, String> {
    let object = out_dir.join("sweep_resources.o");
    let status = Command::new("windres")
        .arg("--input")
        .arg(rc)
        .arg("--output")
        .arg(&object)
        .arg("--output-format=coff")
        .status();

    match status {
        Ok(status) if status.success() => Ok(object),
        Ok(status) => Err(format!("windres exited with {status}")),
        Err(err) => Err(format!("windres is not runnable: {err}")),
    }
}
