id = "remmina"
name = "Remmina"
description = "Remmina remote desktop client: logs and cache (connection profiles are kept)"

[[running]]
type = "exe"
value = "remmina"
os = "linux"

[[var]]
name = "config"
[[var.value]]
os = "linux"
search = "glob"
value = "~/.local/share/remmina"
[[var.value]]
os = "linux"
search = "glob"
value = "~/.config/remmina"

[[option]]
id = "logs"
label = "Logs"
description = "Delete Remmina log files"

[[option.action]]
command = "delete"
search = "glob"
path = "$$config$$/*.log*"
type = "f"

[[option]]
id = "cache"
label = "Cache"
description = "Delete Remmina's cache"

[[option.action]]
command = "delete"
search = "walk.all"
path = "~/.cache/remmina"
