# bash completion for sweep
# Generated by `sweep completions bash` - regenerate after CLI changes.
_sweep() {
    local cur sub opts
    cur="${COMP_WORDS[COMP_CWORD]}"
    # first non-flag word on the line = subcommand
    sub=""
    for w in "${COMP_WORDS[@]:1:COMP_CWORD-1}"; do
        [[ "$w" == -* ]] || { sub="$w"; break; }
    done
    local global_opts="--config --shred --force --trust-external --bleachbit --winapp2 --define --json --summary --quiet --debug --yes --backup-dir --log-file --portable --html --markdown --help --version"
    local subcommands="list info preview clean deepscan leftovers devscan bigfiles dupes wipe schedule undo update-winapp2 hub shred analyze startup services doctor memopt snapshot history watch providers diagnostics import config completions man"
    opts="$global_opts $subcommands"
    case "$sub" in
        list) opts="$global_opts --search --os --running" ;;
        info) opts="$global_opts " ;;
        preview) opts="$global_opts --all --exclude --last --remember" ;;
        clean) opts="$global_opts --all --exclude --last --remember" ;;
        deepscan) opts="$global_opts --pattern --preview" ;;
        leftovers) opts="$global_opts --clean --min-size" ;;
        devscan) opts="$global_opts --clean --max-depth --min-size" ;;
        bigfiles) opts="$global_opts --clean --min-size --older-than --top --max-depth" ;;
        dupes) opts="$global_opts --clean --min-size --max-depth" ;;
        wipe) opts="$global_opts " ;;
        schedule) opts="$global_opts --enable --disable --hour" ;;
        undo) opts="$global_opts --log-file --backup-dir" ;;
        update-winapp2) opts="$global_opts --url" ;;
        hub) opts="$global_opts --url" ;;
        shred) opts="$global_opts " ;;
        analyze) opts="$global_opts --top --max-depth" ;;
        startup) opts="$global_opts " ;;
        services) opts="$global_opts --user" ;;
        doctor) opts="$global_opts " ;;
        memopt) opts="$global_opts " ;;
        snapshot) opts="$global_opts " ;;
        history) opts="$global_opts --log-file --days" ;;
        watch) opts="$global_opts --threshold --interval --once --suggest" ;;
        providers) opts="$global_opts " ;;
        diagnostics) opts="$global_opts " ;;
        import) opts="$global_opts " ;;
        config) opts="$global_opts " ;;
        completions) opts="$global_opts " ;;
        man) opts="$global_opts --output" ;;
    esac
    COMPREPLY=( $(compgen -W "$opts" -- "$cur") )
}
complete -F _sweep sweep
